use anyhow::Result;
use serenity::{
    all::{CommandInteraction, Context, CreateEmbed, CreateInteractionResponse, CreateInteractionResponseMessage, Colour, Timestamp, CreateMessage, ChannelId, GuildId, UserId},
    builder::CreateEmbedFooter,
};
use std::sync::Arc;
use crate::{database::Database, models::*};
use rand::seq::SliceRandom;
use uuid::Uuid;


pub async fn handle_autogen_command(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
) -> Result<()> {
    // Check if user has runner permissions
    if !has_runner_permissions(ctx, interaction, db.clone()).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You need runner permissions to generate teams!")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    let config = db.get_config().await?;
    let queue_players = db.get_queue_waiting(QueueType::Default).await?;
    
    if queue_players.len() < 8 {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ Not enough players in queue (need 8 players)")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Take first 8 players (prioritize by join time)
    let selected_players: Vec<_> = queue_players.into_iter().take(8).collect();
    
    // Generate teams randomly
    let (red_team, blu_team) = {
        let mut ids: Vec<i64> = selected_players.iter().map(|(_, user)| user.id).collect();
        let mut rng = rand::thread_rng();
        ids.shuffle(&mut rng);
        (ids[..4].to_vec(), ids[4..].to_vec())
    };
    
    // Create match
    let match_uuid = Uuid::new_v4().to_string();
    
    let create_match = CreateMatch {
        match_uuid: match_uuid.clone(),
        red_team_channel_id: Some(config.red_channel_id.clone()),
        blu_team_channel_id: Some(config.blu_channel_id.clone()),
        server_channel: Some("A".to_string()), // Default to server A
    };
    
    let match_record = db.create_match(create_match).await?;
    let team_assignment = TeamAssignment { red_team, blu_team };
    db.add_players_to_match(match_record.id, team_assignment.clone()).await?;
    
    // Create team display
    let mut red_names = Vec::new();
    let mut blu_names = Vec::new();
    
    for (_, user) in &selected_players {
        if team_assignment.red_team.contains(&user.id) {
            red_names.push(user.username.clone());
        } else if team_assignment.blu_team.contains(&user.id) {
            blu_names.push(user.username.clone());
        }
    }
    
    let embed = CreateEmbed::new()
        .title("🎮 Teams Generated!")
        .field("🔴 RED Team", red_names.join("\n"), true)
        .field("🔵 BLU Team", blu_names.join("\n"), true)
        .field("ℹ️ Match Info", format!("Match ID: `{}`\nServer: A", match_uuid), false)
        .colour(Colour::from_rgb(81, 207, 102))
        .timestamp(Timestamp::now())
        .footer(CreateEmbedFooter::new("Use /confirm to confirm teams or /regen to regenerate"));
    
    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new().embed(embed)
    );
    
    interaction.create_response(&ctx.http, response).await?;
    
    // Log to admin channel
    if !config.log_channel_id.is_empty() {
        let channel_id: u64 = config.log_channel_id.parse()?;
        let channel = ChannelId::new(channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("📋 Teams Generated")
            .description(format!("Match `{}` teams generated by {}", match_uuid, interaction.user.display_name()))
            .field("🔴 RED", red_names.join(", "), false)
            .field("🔵 BLU", blu_names.join(", "), false)
            .colour(Colour::from_rgb(51, 159, 240))
            .timestamp(Timestamp::now());
        
        channel.send_message(&ctx.http, CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

pub async fn handle_confirm_command(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
    match_id: Option<String>,
) -> Result<()> {
    // Check if user has runner permissions
    if !has_runner_permissions(ctx, interaction, db.clone()).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You need runner permissions to confirm matches!")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Determine match to confirm
    let (match_record_id, match_uuid) = if let Some(uuid) = match_id {
        let m = db.get_match_by_uuid(&uuid).await?;
        (m.id, m.match_uuid.clone())
    } else {
        let m = db.get_latest_forming_match().await?;
        (m.id, m.match_uuid.clone())
    };

    let confirmed_by = interaction.user.id.to_string();
    db.confirm_match(match_record_id, &confirmed_by).await?;
    
    // Move players to voice channels
    move_players_to_team_channels(ctx, db.clone(), match_record_id).await?;
    
    let embed = CreateEmbed::new()
        .title("✅ Match Confirmed!")
        .description(format!("Match `{}` has been confirmed and players moved to voice channels", match_uuid))
        .colour(Colour::from_rgb(81, 207, 102));
    
    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new().embed(embed)
    );
    
    interaction.create_response(&ctx.http, response).await?;
    
    Ok(())
}

pub async fn handle_end_command(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
    match_id: Option<String>,
) -> Result<()> {
    // Check if user has runner permissions
    if !has_runner_permissions(ctx, interaction, db.clone()).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You need runner permissions to end matches!")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Determine match to end
    let (match_record_id, match_uuid) = if let Some(uuid) = match_id {
        let m = db.get_match_by_uuid(&uuid).await?;
        (m.id, m.match_uuid.clone())
    } else {
        let m = db.get_latest_confirmed_match().await?;
        (m.id, m.match_uuid.clone())
    };

    db.end_match(match_record_id).await?;

    // Move players back to queue channel
    move_players_to_queue_channel(ctx, db.clone(), match_record_id).await?;
    
    let embed = CreateEmbed::new()
        .title("🏁 Match Ended!")
        .description(format!("Match `{}` has been ended and players moved back to queue", match_uuid))
        .colour(Colour::from_rgb(255, 107, 107));
    
    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new().embed(embed)
    );
    
    interaction.create_response(&ctx.http, response).await?;
    
    Ok(())
}

async fn has_runner_permissions(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
) -> Result<bool> {
    let config = db.get_config().await?;
    
    if config.runner_role_id.is_empty() && config.admin_role_id.is_empty() {
        return Ok(true); // If no roles configured, allow everyone
    }
    
    let guild_id = interaction.guild_id.ok_or_else(|| anyhow::anyhow!("Not in a guild"))?;
    let member = guild_id.member(&ctx.http, interaction.user.id).await?;
    
    // Check if user has runner or admin role
    let has_runner = !config.runner_role_id.is_empty() && 
        member.roles.iter().any(|r| r.to_string() == config.runner_role_id);
    let has_admin = !config.admin_role_id.is_empty() && 
        member.roles.iter().any(|r| r.to_string() == config.admin_role_id);
    
    Ok(has_runner || has_admin)
}

pub async fn move_players_to_team_channels(
    ctx: &Context,
    db: Arc<Database>,
    match_id: i64,
) -> Result<()> {
    let config = db.get_config().await?;
    let guild_id: GuildId = config.guild_id.parse()?;
    let red_channel: ChannelId = config.red_channel_id.parse()?;
    let blu_channel: ChannelId = config.blu_channel_id.parse()?;
    let players = db.get_match_players(match_id).await?;
    for (discord_id_str, team) in players {
        let user_id: u64 = discord_id_str.parse()?;
        let user = UserId(user_id);
        let dest = if team == "RED" { red_channel } else { blu_channel };
        guild_id.edit_member(&ctx.http, user, |m| m.channel_id(dest)).await?;
    }
    Ok(())
}

pub async fn move_players_to_queue_channel(
    ctx: &Context,
    db: Arc<Database>,
    match_id: i64,
) -> Result<()> {
    let config = db.get_config().await?;
    let guild_id: GuildId = config.guild_id.parse()?;
    let queue_channel: ChannelId = config.queue_channel_id.parse()?;
    let players = db.get_match_players(match_id).await?;
    for (discord_id_str, _) in players {
        let user_id: u64 = discord_id_str.parse()?;
        let user = UserId(user_id);
        guild_id.edit_member(&ctx.http, user, |m| m.channel_id(queue_channel)).await?;
    }
    Ok(())
}
