use serenity::{
    all::{
        CreateEmbed, CreateInteractionResponse, CreateInteractionResponseMessage,
        Context, ChannelId, UserId, RoleId},
};
use serenity::builder::CreateEmbedFooter;
use anyhow::Result;
use crate::{database::Database, models::{player::Player as DbUser, queue::QueueRoleGroup, command::CommandContext}};
use rand::seq::SliceRandom;
use rand::rng;

/// Handles the `/shuffle` command, which shuffles the queue.
pub async fn handle_shuffle_command<'a>(
    cc:    &CommandContext<'a>,
) -> Result<()> {
    // Check permissions
    if !check_runner_permissions(cc).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You don't have permission to use this command.")
                .ephemeral(true)
        );
        cc.intax.create_response(&cc.ctx.http, response).await?;
        return Ok(());
    }

    // Get queued players
    let queue_players = cc.db.get_queue_idle(QueueRoleGroup::Default).await?;
    
    if queue_players.len() < 8 {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content(format!("❌ Not enough players in queue. Need 8, have {}.", queue_players.len()))
                .ephemeral(true)
        );
        cc.intax.create_response(&cc.ctx.http, response).await?;
        return Ok(());
    }

    // Collect players and split into teams (synchronous shuffle so no !Send types live across await)
    let all_players: Vec<DbUser> = queue_players.into_iter().map(|(_, user)| user).collect();
    let (red_team, blu_team) = split_into_teams(&all_players);
    let selected_players: Vec<DbUser> = [red_team.clone(), blu_team.clone()].concat();
    
    // Create session and remove players from queue
    let session = cc.db.create_session(&red_team, &blu_team, "A").await?;
    
    // Remove players from queue
    for player in &selected_players {
        cc.db.leave_queue_by_user_id(player.id).await?;
    }
    
    let red_team_names: Vec<String> = red_team.iter().map(|u| u.name.clone()).collect();
    let blu_team_names: Vec<String> = blu_team.iter().map(|u| u.name.clone()).collect();
    
    let embed = CreateEmbed::new()
        .title("🎲 Teams Generated!")
        .description(format!(
            "**Session ID:** `{}`\n\n**🔴 RED Team:**\n{}\n\n**🔵 BLU Team:**\n{}",
            session.session_uuid,
            red_team_names.join("\n"),
            blu_team_names.join("\n")
        ))
        .color(0x51cf66)
        .footer(CreateEmbedFooter::new("Use /accept to confirm teams"));
    
    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new()
            .embed(embed)
            .ephemeral(true)
    );
    
    intax.create_response(&ctx.http, response).await?;
    
    // Log to channel
    let config = db.get_config().await?;
    if config.log_channel_id != 0 {
        let channel = ChannelId::new(config.log_channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("📋 Session Created")
            .description(format!(
                "**Session:** `{}`\n**Generated by:** {}\n\n**🔴 RED:** {}\n**🔵 BLU:** {}",
                session.session_uuid,
                intax.user.display_name(),
                red_team_names.join(", "),
                blu_team_names.join(", ")
            ))
            .color(0x339af0)
            .footer(CreateEmbedFooter::new("Awaiting acceptance..."));
        
        channel.send_message(&ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

/// Handles the `/accept` command, which accepts a session.
/// 
/// * `ctx`         - Ref to the Serenity context.
/// * `interaction` - Ref to the command interaction.
/// * `db`          - Ref to the database.
/// * `session_id`  - The ID of the session to accept.
pub async fn handle_accept_command<'a>(
    cc:    &CommandContext<'a>,
    session_id: Option<String>,
) -> Result<()> {
    // Check permissions
    if !check_runner_permissions(ctx, intax, &db).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You don't have permission to use this command.")
                .ephemeral(true)
        );
        intax.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Find the session to accept
    let session = if let Some(id) = session_id {
        db.get_session_by_uuid(&id).await?
    } else {
        db.get_latest_hot_session().await?
    };

    // Accept the session
    db.accept_session(session.id).await?;
    
    // Move players to team channels
    move_players_to_team_channels(ctx, &db, session.id, &session.server_channel, intax.guild_id.unwrap()).await?;

    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new()
            .content(format!("✅ Session `{}` accepted! Players moved to team channels.", session.session_uuid))
            .ephemeral(true)
    );
    
    intax.create_response(&ctx.http, response).await?;
    
    // Log acceptance
    let config = db.get_config().await?;
    if config.log_channel_id != 0 {
        let channel = ChannelId::new(config.log_channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("✅ Session Accepted")
            .description(format!(
                "**Session:** `{}`\n**Accepted by:** {}\n**Server:** {}",
                session.session_uuid,
                intax.user.display_name(),
                session.server_channel
            ))
            .color(0x51cf66)
            .footer(CreateEmbedFooter::new("Session in progress..."));
        
        channel.send_message(&ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

/// Handles the `/end` command, which ends a session.
/// 
/// * `ctx`         - Ref to the Serenity context.
/// * `interaction` - Ref to the command interaction.
/// * `db`          - Ref to the database.
/// * `session_id`  - The ID of the session to end.
pub async fn handle_end_command<'a>(
    cc:    &CommandContext<'a>,
    session_id: Option<String>,
) -> Result<()> {
    // Check permissions
    if !check_runner_permissions(ctx, intax, &db).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You don't have permission to use this command.")
                .ephemeral(true)
        );
        intax.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Find the session to end
    let session = if let Some(id) = session_id {
        db.get_session_by_uuid(&id).await?
    } else {
        db.get_latest_push_session().await?
    };

    // End the session
    db.end_session(session.id).await?;
    
    // Move players back to queue channel
    move_players_to_queue_channel(ctx, &db, session.id, intax.guild_id.unwrap()).await?;

    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new()
            .content(format!("🏁 Session `{}` ended! Players moved back to queue.", session.session_uuid))
            .ephemeral(true)
    );
    
    intax.create_response(&ctx.http, response).await?;
    
    // Log session end
    let config = db.get_config().await?;
    if config.log_channel_id != 0 {
        let channel = ChannelId::new(config.log_channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("🏁 Session Ended")
            .description(format!(
                "**Session:** `{}`\n**Ended by:** {}",
                session.session_uuid,
                intax.user.display_name()
            ))
            .color(0xff6b6b)
            .footer(CreateEmbedFooter::new("Session completed"));
        
        channel.send_message(&ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

/// Checks if the user has runner permissions.
/// 
/// * `ctx`         - Ref to the Serenity context.
/// * `interaction` - Ref to the command interaction.
/// * `db`          - Ref to the database.
async fn check_runner_permissions<'a>(
    cc:    &CommandContext<'a>,
) -> Result<bool> {
    let config = db.get_config().await?;
    
    // If no runner roles configured, allow everyone
    if config.runner_role_id != 0 && config.admin_role_id != 0 {
        return Ok(true);
    }
    
    if let Some(guild_id) = intax.guild_id {
        if let Ok(member) = guild_id.member(&ctx.http, intax.user.id).await {
            // Check admin or runner role
            if member.roles.contains(&RoleId::new(config.admin_role_id))
            || member.roles.contains(&RoleId::new(config.runner_role_id)) {
                return Ok(true);
            }
        }
    }
    
    Ok(false)
}

/// Splits the players into two teams.
/// 
/// * `players`     - The players to split into teams.
fn split_into_teams(players: &[DbUser]) -> (Vec<DbUser>, Vec<DbUser>) {
    let mut rng = rng();
    let mut shuffled = players.to_vec();
    shuffled.shuffle(&mut rng);
    let mid = shuffled.len() / 2;
    (shuffled[..mid].to_vec(), shuffled[mid..].to_vec())
}

/// Moves players to their respective team channels.
/// 
/// * `ctx`        - Ref to the Serenity context.
/// * `db`         - Ref to the database.
/// * `session_id` - The ID of the session.
/// * `server`     - The server where the session is taking place.
/// * `guild_id`   - The ID of the guild where the session is taking place.
async fn move_players_to_team_channels(
    ctx: &Context,
    db: &Database,
    session_id: i64,
    server: &str,
    guild_id: serenity::model::id::GuildId,
) -> Result<()> {
    let config = db.get_config().await?;
    let players = db.get_session_players(session_id).await?;
    
    // Select appropriate channels based on server
    let (red_id, blu_id) = match server {
        "B" => (&config.bpug.red_id, &config.bpug.blu_id),
        "C" => (&config.cpug.red_id, &config.cpug.blu_id),
        _ => (&config.apug.red_id, &config.apug.blu_id), // Default to A
    };
    
    for (discord_id, team) in players {
        if let Ok(user_id) = discord_id.parse::<u64>() {
            let target_channel = if team == "RED" { red_id } else { blu_id };
            
            if *target_channel != 0 {
                // Try to move the user
                let _ = ctx.http.edit_member(
                    guild_id,
                    UserId::new(user_id),
                        &serenity::all::EditMember::new().voice_channel(ChannelId::new(*target_channel)),
                        Some("Moving player to team voice channel")
                    ).await;
            }
        }
    }
    
    Ok(())
}

/// Moves players back to the queue channel.
/// 
/// * `ctx`        - Ref to the Serenity context.
/// * `db`         - Ref to the database.
/// * `session_id` - The ID of the session.
/// * `guild_id`   - The ID of the guild where the session is taking place.
async fn move_players_to_queue_channel(
    ctx: &Context,
    db: &Database,
    session_id: i64,
    guild_id: serenity::model::id::GuildId,
) -> Result<()> {
    let config = db.get_config().await?;
    let players = db.get_session_players(session_id).await?;
    
    if config.queue_channel_id != 0 {
        for (discord_id, _) in players {
            if let Ok(user_id) = discord_id.parse::<u64>() {
                // Try to move the user back to queue
                let _ = ctx.http.edit_member(
                    guild_id,
                    UserId::new(user_id),
                    &serenity::all::EditMember::new().voice_channel(ChannelId::new(config.queue_channel_id)),
                    Some("Moving player back to queue voice channel")
                    ).await;
            }
        }
    }
    
    Ok(())
}
