use serenity::{
    all::{
        CreateEmbed, CreateInteractionResponse, CreateInteractionResponseMessage,
        CommandInteraction, Context, ChannelId, UserId, RoleId},
};
use serenity::builder::CreateEmbedFooter;
use anyhow::Result;
use crate::{database::Database, models::{user::User as DbUser, queue::QueueType}};
use std::sync::Arc;
use rand::seq::SliceRandom;
use rand::thread_rng;

pub async fn handle_shuffle_command(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
) -> Result<()> {
    // Check permissions
    if !check_runner_permissions(ctx, interaction, &db).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You don't have permission to use this command.")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Get queued players
    let queue_players = db.get_queue_idle(QueueType::Default).await?;
    
    if queue_players.len() < 8 {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content(format!("❌ Not enough players in queue. Need 8, have {}.", queue_players.len()))
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Collect players and split into teams (synchronous shuffle so no !Send types live across await)
    let all_players: Vec<DbUser> = queue_players.into_iter().map(|(_, user)| user).collect();
    let (red_team, blu_team) = split_into_teams(&all_players);
    let selected_players: Vec<DbUser> = [red_team.clone(), blu_team.clone()].concat();
    
    // Create session and remove players from queue
    let session = db.create_session(&red_team, &blu_team, "A").await?;
    
    // Remove players from queue
    for player in &selected_players {
        db.leave_queue_by_user_id(player.id).await?;
    }
    
    let red_team_names: Vec<String> = red_team.iter().map(|u| u.username.clone()).collect();
    let blu_team_names: Vec<String> = blu_team.iter().map(|u| u.username.clone()).collect();
    
    let embed = CreateEmbed::new()
        .title("🎲 Teams Generated!")
        .description(format!(
            "**Session ID:** `{}`\n\n**🔴 RED Team:**\n{}\n\n**🔵 BLU Team:**\n{}",
            session.session_uuid,
            red_team_names.join("\n"),
            blu_team_names.join("\n")
        ))
        .color(0x51cf66)
        .footer(CreateEmbedFooter::new("Use /accept to confirm teams"));
    
    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new()
            .embed(embed)
            .ephemeral(true)
    );
    
    interaction.create_response(&ctx.http, response).await?;
    
    // Log to channel
    let config = db.get_config().await?;
    if !config.log_channel_id.is_empty() {
        let channel_id: u64 = config.log_channel_id.parse()?;
        let channel = ChannelId::new(channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("📋 Session Created")
            .description(format!(
                "**Session:** `{}`\n**Generated by:** {}\n\n**🔴 RED:** {}\n**🔵 BLU:** {}",
                session.session_uuid,
                interaction.user.display_name(),
                red_team_names.join(", "),
                blu_team_names.join(", ")
            ))
            .color(0x339af0)
            .footer(CreateEmbedFooter::new("Awaiting acceptance..."));
        
        channel.send_message(&ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

pub async fn handle_accept_command(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
    session_id: Option<String>,
) -> Result<()> {
    // Check permissions
    if !check_runner_permissions(ctx, interaction, &db).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You don't have permission to use this command.")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Find the session to accept
    let session = if let Some(id) = session_id {
        db.get_session_by_uuid(&id).await?
    } else {
        db.get_latest_hot_session().await?
    };

    // Accept the session
    db.accept_session(session.id).await?;
    
    // Move players to team channels
    move_players_to_team_channels(ctx, &db, session.id, &session.server_channel, interaction.guild_id.unwrap()).await?;

    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new()
            .content(format!("✅ Session `{}` accepted! Players moved to team channels.", session.session_uuid))
            .ephemeral(true)
    );
    
    interaction.create_response(&ctx.http, response).await?;
    
    // Log acceptance
    let config = db.get_config().await?;
    if !config.log_channel_id.is_empty() {
        let channel_id: u64 = config.log_channel_id.parse()?;
        let channel = ChannelId::new(channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("✅ Session Accepted")
            .description(format!(
                "**Session:** `{}`\n**Accepted by:** {}\n**Server:** {}",
                session.session_uuid,
                interaction.user.display_name(),
                session.server_channel
            ))
            .color(0x51cf66)
            .footer(CreateEmbedFooter::new("Session in progress..."));
        
        channel.send_message(&ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

pub async fn handle_end_command(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: Arc<Database>,
    session_id: Option<String>,
) -> Result<()> {
    // Check permissions
    if !check_runner_permissions(ctx, interaction, &db).await? {
        let response = CreateInteractionResponse::Message(
            CreateInteractionResponseMessage::new()
                .content("❌ You don't have permission to use this command.")
                .ephemeral(true)
        );
        interaction.create_response(&ctx.http, response).await?;
        return Ok(());
    }

    // Find the session to end
    let session = if let Some(id) = session_id {
        db.get_session_by_uuid(&id).await?
    } else {
        db.get_latest_push_session().await?
    };

    // End the session
    db.end_session(session.id).await?;
    
    // Move players back to queue channel
    move_players_to_queue_channel(ctx, &db, session.id, interaction.guild_id.unwrap()).await?;

    let response = CreateInteractionResponse::Message(
        CreateInteractionResponseMessage::new()
            .content(format!("🏁 Session `{}` ended! Players moved back to queue.", session.session_uuid))
            .ephemeral(true)
    );
    
    interaction.create_response(&ctx.http, response).await?;
    
    // Log session end
    let config = db.get_config().await?;
    if !config.log_channel_id.is_empty() {
        let channel_id: u64 = config.log_channel_id.parse()?;
        let channel = ChannelId::new(channel_id);
        
        let log_embed = CreateEmbed::new()
            .title("🏁 Session Ended")
            .description(format!(
                "**Session:** `{}`\n**Ended by:** {}",
                session.session_uuid,
                interaction.user.display_name()
            ))
            .color(0xff6b6b)
            .footer(CreateEmbedFooter::new("Session completed"));
        
        channel.send_message(&ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }
    
    Ok(())
}

async fn check_runner_permissions(
    ctx: &Context,
    interaction: &CommandInteraction,
    db: &Database,
) -> Result<bool> {
    let config = db.get_config().await?;
    
    // If no runner roles configured, allow everyone
    if config.runner_role_id.is_empty() && config.admin_role_id.is_empty() {
        return Ok(true);
    }
    
    if let Some(guild_id) = interaction.guild_id {
        if let Ok(member) = guild_id.member(&ctx.http, interaction.user.id).await {
            // Check admin roles
            if let Ok(role_id) = config.admin_role_id.parse::<u64>() {
                if member.roles.contains(&RoleId::new(role_id)) {
                    return Ok(true);
                }
            }
            
            // Check runner roles
            if let Ok(role_id) = config.runner_role_id.parse::<u64>() {
                if member.roles.contains(&RoleId::new(role_id)) {
                    return Ok(true);
                }
            }
        }
    }
    
    Ok(false)
}

fn split_into_teams(players: &[DbUser]) -> (Vec<DbUser>, Vec<DbUser>) {
    let mut rng = thread_rng();
    let mut shuffled = players.to_vec();
    shuffled.shuffle(&mut rng);
    let mid = shuffled.len() / 2;
    (shuffled[..mid].to_vec(), shuffled[mid..].to_vec())
}

async fn move_players_to_team_channels(
    ctx: &Context,
    db: &Database,
    session_id: i64,
    server: &str,
    guild_id: serenity::model::id::GuildId,
) -> Result<()> {
    let config = db.get_config().await?;
    let players = db.get_session_players(session_id).await?;
    
    // Select appropriate channels based on server
    let (red_channel_id, blu_channel_id) = match server {
        "B" => (&config.red_b_channel_id, &config.blu_b_channel_id),
        "C" => (&config.red_c_channel_id, &config.blu_c_channel_id),
        _ => (&config.red_a_channel_id, &config.blu_a_channel_id), // Default to A
    };
    
    for (discord_id, team) in players {
        if let Ok(user_id) = discord_id.parse::<u64>() {
            let target_channel = if team == "RED" { red_channel_id } else { blu_channel_id };
            
            if !target_channel.is_empty() {
                if let Ok(channel_id) = target_channel.parse::<u64>() {
                    // Try to move the user
                    let _ = ctx.http.edit_member(
                        guild_id,
                        UserId::new(user_id),
                        &serenity::all::EditMember::new().voice_channel(ChannelId::new(channel_id)),
                        Some("Moving player to team voice channel")
                    ).await;
                }
            }
        }
    }
    
    Ok(())
}

async fn move_players_to_queue_channel(
    ctx: &Context,
    db: &Database,
    session_id: i64,
    guild_id: serenity::model::id::GuildId,
) -> Result<()> {
    let config = db.get_config().await?;
    let players = db.get_session_players(session_id).await?;
    
    if !config.queue_channel_id.is_empty() {
        if let Ok(queue_channel_id) = config.queue_channel_id.parse::<u64>() {
            for (discord_id, _) in players {
                if let Ok(user_id) = discord_id.parse::<u64>() {
                    // Try to move the user back to queue
                    let _ = ctx.http.edit_member(
                        guild_id,
                        UserId::new(user_id),
                        &serenity::all::EditMember::new().voice_channel(ChannelId::new(queue_channel_id)),
                        Some("Moving player back to queue voice channel")
                    ).await;
                }
            }
        }
    }
    
    Ok(())
}
