// CHECK ME
use std::sync::Arc;

use anyhow::{anyhow, Result};
use rand::rng;
use rand::seq::SliceRandom;
use serenity::all::{ChannelId, Context, CreateEmbed, CreateInteractionResponse, CreateInteractionResponseMessage, EditMember, GuildId, UserId};
use serenity::builder::CreateEmbedFooter;
use tracing::info;

use crate::database::Database;
use crate::handlers::role::check_role;
use crate::models::command::CommandContext;
use crate::models::player::Role;
use crate::models::session::{Group, Session, SessionPlayer, SessionStatus, Team};

/// Splits the players into two teams.
///
/// * `players` - The players to split into teams.
pub fn split_into_teams(players: &[SessionPlayer]) -> (Vec<SessionPlayer>, Vec<SessionPlayer>) {
    let mut rng = rng();
    let mut player_list: Vec<SessionPlayer> = players.to_vec();
    player_list.shuffle(&mut rng);
    let team_size = player_list.len() / 2;
    let team1 = player_list[0..team_size].to_vec();
    let team2 = player_list[team_size..].to_vec();
    (team1, team2)
}

/// Handles the `/shuffle` command, which shuffles the queue.
pub async fn shuffle(cc: &CommandContext<'_>) -> Result<()> {
    info!("[session.rs] Processing shuffle command");
    // Check permissions
    if !check_role(cc, &Role::Runner).await? {
        cc.create_bot_reply("Only runners can shuffle teams!").await?;
        return Ok(());
    }

    // Get active group with session
    // TODO: Replace 0 with the actual queue channel ID for the group you want
    let group = cc.db.get_group(0).await?; // <-- FIX: supply correct queue_id

    if group.session.is_empty() {
        cc.create_bot_reply("No active sessions.").await?;
        return Ok(());
    }

    let session = group.session.last().unwrap();

    if session.pool.len() < 8 {
        cc.create_bot_reply(&format!("Not enough players in session. Need {} more.", 8 - session.pool.len())).await?;
        return Ok(());
    }

    // Collect players and split into teams (synchronous shuffle so no !Send types live across await)
    let (mut red_team, mut blu_team) = split_into_teams(&session.pool);
    let mut updated_group = group.clone();

    // Assign teams using SessionPlayer's team method
    for sp in &mut red_team {
        sp.team(Team::Red);
    }
    for sp in &mut blu_team {
        sp.team(Team::Blu);
    }

    // Update pool with new team assignments
    updated_group.session.last_mut().unwrap().pool.clear();
    updated_group.session.last_mut().unwrap().pool.extend(red_team.into_iter());
    updated_group.session.last_mut().unwrap().pool.extend(blu_team.into_iter());

    updated_group.session.last_mut().unwrap().status = SessionStatus::Hot;
    // TODO: Persist updated_group changes to DB if needed (no update_group method exists)
    // You may need to implement this in your database layer.

    let red_team_names: Vec<String> = updated_group.session
                                                   .last()
                                                   .unwrap()
                                                   .pool
                                                   .iter()
                                                   .filter(|sp| sp.team == Some(Team::Red))
                                                   .map(|sp| format!("<@{}>", sp.player.discord_id))
                                                   .collect();
    let blu_team_names: Vec<String> = updated_group.session
                                                   .last()
                                                   .unwrap()
                                                   .pool
                                                   .iter()
                                                   .filter(|sp| sp.team == Some(Team::Blu))
                                                   .map(|sp| format!("<@{}>", sp.player.discord_id))
                                                   .collect();

    let embed = CreateEmbed::new().title("Teams Generated!")
                                  .description(format!("**Session ID:** `{}`\n\n**🔴 RED Team:**\n{}\n\n**🔵 BLU Team:**\n{}",
                                                       stringify!(updated_group.session.last().unwrap().id),
                                                       red_team_names.join("\n"),
                                                       blu_team_names.join("\n")))
                                  .footer(CreateEmbedFooter::new("Use /accept to confirm teams"));

    let response = CreateInteractionResponse::Message(CreateInteractionResponseMessage::new().embed(embed).ephemeral(true));

    cc.intax.create_response(&cc.ctx.http, response).await?;

    // Log to channel
    let config = cc.db.get_config().await?;
    if config.ic_log != 0 {
        let channel = ChannelId::new(config.ic_log);

        let log_embed = CreateEmbed::new().title("Session Created")
                                          .description(format!("**Session:** `{}`\n**Generated by:** {}\n\n**🔴 RED:** {}\n**🔵 BLU:** {}",
                                                               stringify!(updated_group.sessions.last().unwrap().id),
                                                               cc.intax.user.display_name(),
                                                               red_team_names.join(", "),
                                                               blu_team_names.join(", ")))
                                          .footer(CreateEmbedFooter::new("Awaiting acceptance..."));

        channel.send_message(&cc.ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }

    Ok(())
}

/// Handles the `/accept` command, which accepts a session.
///
/// * `ctx`         - Ref to the Serenity context.
/// * `interaction` - Ref to the command interaction.
/// * `db`          - Ref to the database.
/// * `session_id`  - The ID of the session to accept.
pub async fn accept(cc: &CommandContext<'_>, i_session: &Option<String>) -> Result<()> {
    info!("[session.rs] Processing accept command for session ID: {}", i_session.clone().unwrap_or("None".to_string()));
    // Check permissions
    if !check_role(cc, &Role::Runner).await? {
        cc.create_bot_reply("Only runners can accept sessions!").await?;
        return Ok(());
    }

    // Get the group with active session
    // TODO: Replace 0 with the actual queue channel ID for the group you want
    let mut group = cc.db.get_group(0).await?; // <-- FIX: supply correct queue_id

    // If a specific session ID was provided, ensure it matches
    if let Some(id) = i_session.clone() {
        // Convert both ids to strings for comparison
        let session_id_str = format!("{:?}", group.session.last().unwrap().id);
        if session_id_str != id {
            cc.create_bot_reply(&format!("Session ID {} not found.", id)).await?;
            return Ok(());
        }
    }

    // Update session status to Push
    group.session.last_mut().unwrap().status = SessionStatus::Push;
    info!("[session.rs] Updating session status to PUSH");
    // TODO: Persist group changes to DB if needed (no update_group method exists)
    // You may need to implement this in your database layer.

    // Move players to team channels
    move_players_to_team_channels(cc.ctx, &cc.db, &group, group.session.last().unwrap(), cc.intax.guild_id.unwrap()).await?;

    cc.create_bot_reply("Session accepted! Players moved to team channels.").await?;

    // Log acceptance
    let config = cc.db.get_config().await?;
    if config.ic_log != 0 {
        let channel = ChannelId::new(config.ic_log);

        let log_embed = CreateEmbed::new().title("Session Accepted")
                                          .description(format!("**Session ID:** `{:?}`\n**Accepted by:** {}", group.session.last().unwrap().id, cc.intax.user.display_name()))
                                          .footer(CreateEmbedFooter::new("Session in progress..."));

        channel.send_message(&cc.ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }

    Ok(())
}

/// Handles the `/end` command, which ends a session.
///
/// * `ctx`         - Ref to the Serenity context.
/// * `interaction` - Ref to the command interaction.
/// * `db`          - Ref to the database.
/// * `session_id`  - The ID of the session to end.
pub async fn end(cc: &CommandContext<'_>, session_id: Option<String>) -> Result<()> {
    info!("[session.rs] Processing end command for session ID: {}", session_id.clone().unwrap_or("None".to_string()));
    // Check permissions
    if !check_role(cc, &Role::Runner).await? {
        cc.create_bot_reply("Only runners can end sessions!").await?;
        return Ok(());
    }

    // TODO: Replace 0 with the actual queue channel ID for the group you want
    let mut group = cc.db.get_group(0).await?; // <-- FIX: supply correct queue_id

    // Find the session to end based on ID or status
    let session_index = if let Some(id) = session_id.clone() {
        // Find session with matching ID
        group.session.iter().position(|s| format!("{:?}", s.id) == id)
    } else {
        // Find session with Push status
        group.session.iter().position(|s| s.status == SessionStatus::Push)
    };

    if let Some(index) = session_index {
        // Set the session status to Pull (ended)
        group.session[index].status = SessionStatus::Pull;

        // TODO: Persist group changes to DB if needed (no update_group method exists)
        // You may need to implement this in your database layer.

        // Move players to queue channel if we're in a guild
        if let Some(guild_id) = cc.intax.guild_id {
            move_players_to_queue_channel(cc.ctx, &cc.db, &group, &group.session[index], guild_id).await?;
        }
    } else {
        cc.create_bot_reply("No active session found to end.").await?;
        return Ok(());
    }

    let session_id_display = if let Some(idx) = session_index {
        format!("{:?}", group.session[idx].id)
    } else {
        "unknown".to_string()
    };

    cc.create_bot_reply(&format!("Session {} has been ended. Players will be moved back to queue.", session_id_display))
      .await?;

    // Log session end
    let config = cc.db.get_config().await?;
    if config.ic_log != 0 {
        let channel = ChannelId::new(config.ic_log);

        let log_embed = CreateEmbed::new().title("Session Ended")
                                          .description(format!("**Session ID:** `{:?}`\n**Ended by:** {}", session_id_display, cc.intax.user.display_name()))
                                          .footer(CreateEmbedFooter::new("Session completed"));

        channel.send_message(&cc.ctx.http, serenity::all::CreateMessage::new().embed(log_embed)).await?;
    }

    Ok(())
}

/// Moves players back to the queue channel.
///
/// * `ctx`        - Ref to the Serenity context.
/// * `db`         - Ref to the database.
/// * `group`      - The group containing session and queue info.
/// * `session`    - The session with players to move.
/// * `guild_id`   - The ID of the guild where the session is taking place.
async fn move_players_to_queue_channel(ctx: &Context, _db: &Arc<Database>, group: &Group, session: &Session, guild_id: GuildId) -> Result<()> {
    // Check if queue channel is configured
    if group.queue != 0 {
        for player in &session.pool {
            let user_id = player.player.discord_id;
            // Try to move the user back to queue
            let _ = ctx.http
                       .edit_member(guild_id,
                                    UserId::new(user_id),
                                    &EditMember::new().voice_channel(ChannelId::new(group.queue)),
                                    Some("Moving player back to queue voice channel"))
                       .await;
        }
    }
    Ok(())
}

/// Moves players to their respective team channels.
///
/// * `ctx`        - Ref to the Serenity context.
/// * `db`         - Ref to the database.
/// * `group`      - The group containing team channel information.
/// * `session`    - The session with assigned teams.
/// * `guild_id`   - The ID of the guild where the session is taking place.
async fn move_players_to_team_channels(ctx: &Context, _db: &Arc<Database>, group: &Group, session: &Session, guild_id: GuildId) -> Result<()> {
    // Get red/blue voice channel IDs from the first team in the group
    if group.teams.is_empty() {
        return Err(anyhow!("No team channels configured for this group"));
    }
    let red_channel_id = group.teams[0].red;
    let blue_channel_id = group.teams[0].blu;
    if red_channel_id == 0 || blue_channel_id == 0 {
        return Err(anyhow!("Voice channel IDs not configured for this group"));
    }
    let redvc = ChannelId::new(red_channel_id);
    let bluvc = ChannelId::new(blue_channel_id);

    // Move players to red/blu voice channels
    for player in &session.pool {
        if let Some(team) = &player.team {
            let target_channel = match team {
                Team::Red => redvc,
                Team::Blu => bluvc,
            };
            let user_id = player.player.discord_id;
            if let Ok(mut member) = guild_id.member(&ctx.http, user_id).await {
                let _ = member.edit(&ctx.http, EditMember::new().voice_channel(target_channel)).await;
            }
        }
    }

    Ok(())
}
